spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/flow
    #    url: jdbc:h2:tcp://localhost/~/flow
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 1000
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    org.hibernate:
      SQL: debug
      type: trace
